import type { Produit } from './types'

// Temporary data matching docs/maquettes/Catalogue.png, until the backend exposes /api/produits.
export const mockProduits: Produit[] = [
  {
    id: 1,
    nom: 'Tuque en laine mérinos',
    categorie: { id: 4, nom: 'Accessoire' },
    prix: 38,
    enStock: true,
    enPromotion: false,
    badge: 'Nouveau',
    rangPopularite: 1,
    dateAjout: '2026-09-20',
    couleur: '#d8c7b3',
  },
  {
    id: 2,
    nom: 'Tasse en grès émaillé',
    categorie: { id: 1, nom: 'Maison' },
    prix: 32,
    enStock: true,
    enPromotion: true,
    rangPopularite: 2,
    dateAjout: '2026-06-02',
    couleur: '#c5d0c8',
  },
  {
    id: 3,
    nom: 'Bougie sapin baumier',
    categorie: { id: 1, nom: 'Maison' },
    prix: 28,
    enStock: true,
    enPromotion: false,
    rangPopularite: 3,
    dateAjout: '2026-07-14',
    couleur: '#bccab0',
  },
  {
    id: 4,
    nom: 'Sirop d’érable ambré 540 ml',
    categorie: { id: 3, nom: 'Épicerie' },
    prix: 16.5,
    enStock: true,
    enPromotion: false,
    badge: 'Populaire',
    rangPopularite: 4,
    dateAjout: '2026-03-10',
    couleur: '#e3b572',
  },
  {
    id: 5,
    nom: 'Jeté en laine tissé',
    categorie: { id: 1, nom: 'Maison' },
    prix: 145,
    enStock: true,
    enPromotion: false,
    badge: 'Stock limité',
    rangPopularite: 5,
    dateAjout: '2026-08-28',
    couleur: '#d7b8ab',
  },
  {
    id: 6,
    nom: 'Planche à découper en érable',
    categorie: { id: 2, nom: 'Cuisine' },
    prix: 64,
    enStock: true,
    enPromotion: true,
    rangPopularite: 6,
    dateAjout: '2026-05-05',
    couleur: '#d9bf92',
  },
  {
    id: 7,
    nom: 'Chaussettes de laine',
    categorie: { id: 4, nom: 'Accessoire' },
    prix: 24,
    enStock: false,
    enPromotion: false,
    badge: 'Rupture',
    rangPopularite: 7,
    dateAjout: '2026-02-18',
    couleur: '#b7bfcc',
  },
  {
    id: 8,
    nom: 'Beurre d’érable 250 g',
    categorie: { id: 3, nom: 'Épicerie' },
    prix: 11,
    enStock: true,
    enPromotion: false,
    rangPopularite: 8,
    dateAjout: '2026-04-22',
    couleur: '#ead0a0',
  },
]
